In [1]:
import pandas as pd

In [2]:
users_csv_path = "./Datasets/Twitter_Users.csv"

twitter_users = pd.read_csv(users_csv_path, encoding='latin1')

twitter_users

,Twitter_User_Name,Following,Followers,Verified,Link,Location,Real_Location
0,#winelover bot,2,594,0,https://twitter.com/winelover_bot?s=20,#Winesphere,0.0
1,Aaron Chewning,1404,41400,0,https://twitter.com/AaronChewning?s=20,Atlanta,1.0
2,Accidental Haiku,1,3653,0,https://twitter.com/accidental575?s=20,NaN,NaN
3,Ace Attorney Bot,5,4700,0,https://twitter.com/aceattorneybot?s=20,Defendant Lobby No. 2,0.0
4,Alex Holley,518,101000,0,https://twitter.com/AlexHolleyFOX29?s=20,Philadelphia,1.0
...,...,...,...,...,...,...,...
91,here's your reminder,2,143500,0,https://twitter.com/tinycarebot?s=20,NaN,NaN
92,hi i have advice,0,3926,0,https://twitter.com/nice_tips_bot?s=20,NaN,NaN
93,olivia taters,4557,5598,0,https://twitter.com/oliviataters?s=20,NaN,NaN
94,portmanteau_bot,0,1960,0,https://twitter.com/portmanteau_bot?s=20,NaN,NaN
95,waqas Sajid,1817,963,0,https://twitter.com/wqs47?s=20,Islamabad,1.0

In [3]:
tweets_csv_path = "./Datasets/Twitter_Data.csv"

twitter_tweets = pd.read_csv(tweets_csv_path, encoding='latin1')

twitter_tweets

,Twitter_User_Name,Twitter_Account,Twitter_User_Description,Tweet_id,Tweet_created_at,Tweet_text,Label
0,Museum Bot,MuseumBot,I am a bot that tweets a random high-res Open ...,802757608646082560,2016-11-27 06:15:03,b'Imperial Theatrical Coat for Court Lady http...,0
1,Horse ebooks,Horse_ebooks,Horse ebooks,360700292859310080,2013-07-26 09:57:05,b'You ll do exercises that focus like LASERBEA...,0
2,Garry12gg,garry12gg,I like to learn new things and play video games.,976198950830133259,2018-03-20 20:49:01,"b'RT @skrongstyle: Marvel: ""Infinity War is th...",0
3,Sadiq Khan,SadiqKhan,Mayor of London. #TeamKhan,969218828696719361,2018-03-01 14:32:30,b'To the one million EU citizens across our ci...,1
4,Ace Attorney Bot,aceattorneybot,No clues here. (unofficial and not even remote...,1066842747636670465,2018-11-25 23:55:06,b'(Words cannot describe how screwed I am...)',0
...,...,...,...,...,...,...,...
292621,Security News Bot,SecurityNewsbot,Tweeting all things #InfoSec #Cybercrime #DDoS...,1069139152535400448,2018-12-02 08:00:12,b'#WordPress wawp_framework Plugins 1.0 Databa...,0
292622,Mishal Awan,MishalAwan13,A true Patriot,1069864927932936193,2018-12-04 08:04:10,b'India is funding Dawn for propagating agains...,1
292623,Robots Rule,RobotzRule,"I love robots, and I retweet stories about the...",874525002816794624,2017-06-13 07:13:03,b'RT @BrownEdwardsEDU: According to Mark Cuban...,0
292624,Jen Spyra,jenspyra,"Writer for @colbertlateshow, formerly for @the...",713811777415471104,2016-03-26 19:36:04,"b""@joshgondelman @ArielDumas (that's the hamil...",1
292625,Security News Bot,SecurityNewsbot,Tweeting all things #InfoSec #Cybercrime #DDoS...,1060358790015463424,2018-11-08 02:30:10,b'#Oracle #Linux 7 : jasper (ELSA-2018-3253) h...,0